name: Build and Upload Artifacts
inputs: {}
description: Build the static site and upload it as a workflow artifact.
runs:
  using: "composite"
  steps:
    - name: Build static site
      shell: bash
      run: |
        python scripts/build_static.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: static-site
        path: dist
